SSR support
ktsstudio/mediaproject-style pull request #11
Opened 2023-04-13 08:00 UTC by wayvy

2023-04-20 13:29 UTC, n-merkulova reviewed
в целом не очень поняла суть изменений. что такого было раньше, что не давало библиотеке работать с ssr? условие на обращение к window?

2023-04-20 13:29 UTC, n-merkulova commented on package.json
> +    "styled-components": "^5.3.3"
тут не поняла. разве так не получится, что и в библиотеке будет версия библиотеки, и в проекте? вроде цель как раз в том, чтобы тянуть этот пакет в либу из проекта

2023-04-20 17:06 UTC, AliceSitedge commented on src/types/window.ts
> -export type WindowType = Pick<CommonWindowType, 'is_mobile'>;
Не поддерживает, была цель убрать ее из зависимостей

2023-04-20 17:59 UTC, AliceSitedge commented on package.json
> +  "version": "3.1.0",
Тут изменилась сигнатура функции markup, нужно мажорный релиз делать

2023-04-20 17:59 UTC, AliceSitedge commented on src/types/window.ts
> -import { WindowType as CommonWindowType } from '@ktsstudio/mediaproject-utils';
А вообще если импортировать только тип из mediaproject-utils, или импортировать его по точному пути, тоже падает установка библиотеки?

2023-06-05 12:19 UTC, AliceSitedge commented on package.json
> +    "styled-components": "^5.3.3"
Да, тогда логичнее в peerDependencies все же оставить

2023-06-16 09:04 UTC, AliceSitedge requested changes

2023-06-16 09:04 UTC, AliceSitedge commented on src/markup.ts
> +  checkMobile: defaultCheckMobile,
Вообще мне кажется, что можно отказаться от параметров `withCheckMobile` и `checkMobile`, а просто уже передавать параметр `isMobile`. Чтоб внутри вообще не было обращения к `window.is_mobile`

2023-12-29 10:13 UTC, kurakinasv commented
Проверяла на [цифровых учителях](https://git.kts.tech/mailru-nonstandart/digital-teachers-landing-front)

**Тестинг** 

1. Добавить файл .env с переменными окружения
2. В корне проекта: `yarn add @ktsstudio/mediaproject-style && yarn dev`
3. Импортировать + заменить существующие миксины на миксины для styled-components
4. Словить ошибку типа _SyntaxError: Cannot use import statement outside a module_
5. Связать проект с изменениями в библиотеке – в mediaproject-style выполнить: `yarn link && yarn build`
6. В проекте: `yarn link @ktsstudio/mediaproject-style && yarn dev`
7. Ошибка исчезнет

**Обнуление** 

1. В проекте выполнить: `yarn unlink @ktsstudio/mediaproject-style`
2. В mediaproject-style: `yarn unlink`

2023-12-29 17:10 UTC, AliceSitedge requested changes

2023-12-29 17:12 UTC, AliceSitedge commented on package.json
> +    "styled-components": "^5.3.3"
Тут нужно удалить styled-components и @types/styled-components из dependencies и добавить их в devDependencies и peerDependencies

2024-01-09 14:46 UTC, AliceSitedge approved these changes

2024-02-05 12:59 UTC, Christik commented
Изменения из ПРа были перенесены в #13

2024-02-05 12:59 UTC, closed without merging