Релиз 4.0.0
ktsstudio/mediaproject-style pull request #13
Opened 2024-01-31 13:23 UTC by Christik

**Задачка:**
- [SPECIAL-14192](https://youtrack.kts.studio/issue/SPECIAL-14192) Релиз 4.0.0

**Что сделано:**
- Слила в одну ветки с [добавлением поддержки SSR](https://github.com/ktsstudio/mediaproject-style/pull/11) и с [обновлением markup и миксинов](https://github.com/ktsstudio/mediaproject-style/pull/12)
- Убрала из обновленной утилиты markup `checkMobile()` и добавила поле `isMobile`
- Протестировала на цифровых учителях с помощью `yarn link`:
  - styled component и scss миксины работают норм
  - Заменила `<script src="/lib/initMarkup.js" defer />` на инициализацию новой утилиты `initMarkup({...})`. Если инициировать `markup` в `useEffect` компонента лэйаута страницы, то все работает без ошибок, верстка остается прежней.
  - Протестировала настройки конфига `markup`, в частности `isMobile`

2024-02-02 10:54 UTC, AliceSitedge requested changes

2024-02-02 10:54 UTC, AliceSitedge commented on CHANGELOG.md
> +- [*] миксины `backgroundImageCover`, `backgroundImageContain`, `centerPos`
Дописать бы, что именно в них доработали

2024-02-02 10:54 UTC, AliceSitedge commented on package.json
> +    "mobx": "^6.12.0",
Не думаю, что Markup должен быть mobx-стором, он тянет лишнюю зависимость в либу. Я бы просто классом оставила

2024-02-02 10:54 UTC, AliceSitedge commented on src/markup/Markup.ts
> +    return debounce(this.fit.bind(this));
Может throttle использовать? Чтобы при долгом изменении размеров окна все-таки верстка менялась, а не ждала, пока изменения перестанут происходить

2024-02-02 10:54 UTC, AliceSitedge commented on src/markup/Markup.ts
> +      this._currentHtmlFontSize = this._maxFontSize;
Как будто лучше не переопределять поле, а изначально устанавливать значение с учетом ограничений. Например, метод-сеттер сделать, где будет проверка максимального и минимального значений

2024-02-02 10:54 UTC, AliceSitedge commented on src/markup/Markup.ts
> +    this._currentWindowSize = {
А нужно ли хранить текущие размеры окна, если они используются только для вычисления шрифта в моменте?

2024-02-02 10:54 UTC, AliceSitedge commented on src/mixins.scss
>    left: 50%;
Нужно тогда тоже вычислить в зависимости от оси

2024-02-02 10:54 UTC, AliceSitedge commented on src/mixins.scss
> +  transform: $translate map.get($config, properties);
Точно работает без join-а при передаче нескольких параметров?

2024-02-02 10:54 UTC, AliceSitedge commented on src/mixins.scss
> +@mixin ratioWidthHeight($width, $height, $factor: 1) {
Может scale вместо ratio?

2024-02-02 10:54 UTC, AliceSitedge commented on src/mixins.scss
> +/// Фиксит в safari мерцание острых углов при overflow:hidden и border-radius
Вот здесь не хватает какой-то ссылки на stackoverflow либо описание, что это за картинка

2024-02-02 10:54 UTC, AliceSitedge commented on src/mixins.ts
> +  `;
И тут для этого миксина аналогичные комменты, как в scss

2024-02-02 10:54 UTC, AliceSitedge commented on src/mixins.ts
> + * Здесь data:image/png - это квадратное изображение 1x1 с черным фоном
А, вот коммент. Тогда еще в scss добавить нужно

2024-02-05 04:02 UTC, Christik commented on package.json
> +    "mobx": "^6.12.0",
Mobx добавила, чтобы можно было отслеживать изменение `currentHtmlFontSize` при ресайзе окна. Иначе это поле не обновляется. Убрать все-таки mobx?

2024-02-05 04:04 UTC, Christik commented on src/mixins.scss
> +  transform: $translate map.get($config, properties);
Да, тестила с разными параметрами. Без join работает, потому что в параметрах передается строка без запятых.

2024-02-05 04:14 UTC, Christik commented on src/mixins.scss
> +/// Фиксит в safari мерцание острых углов при overflow:hidden и border-radius
Когда-то подсмотрела этот фикс на stackoverflow, но сейчас не могу найти ссылку)) Он давно кочует у меня из проекта в проект.

2024-02-05 12:19 UTC, AliceSitedge commented on src/mixins.scss
> +/// Фиксит в safari мерцание острых углов при overflow:hidden и border-radius
Оки, тогда думаю описания, что это черный квадрат, хватит

2024-02-07 07:54 UTC, AliceSitedge approved these changes

2024-02-07 07:55 UTC, merged